name: unmaterialistic
description: A custom_lint for warning you against using 'package:flutter/material.dart'.
version: 0.0.1-dev.1
repository: https://github.com/Luckey-Elijah/unmaterialistic_lint

environment:
  sdk: ^3.5.4

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
